/**
 * Generate TypeScript types from OpenAPI specification
 *
 * This script reads the OpenAPI spec from static/openapi.json and generates
 * TypeScript types using openapi-typescript. The generated types are used
 * by openapi-fetch for type-safe API calls.
 *
 * Usage: npx tsx scripts/generate-api-types.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';

const OPENAPI_PATH = path.resolve(import.meta.dirname, '../static/openapi.json');
const OUTPUT_PATH = path.resolve(import.meta.dirname, '../src/lib/api/schema.d.ts');

/**
 * Fix known issues in the OpenAPI spec before processing:
 * - utoipa generates invalid $ref to TupleUnit for Rust () types
 */
function fixSchema(schema: Record<string, unknown>): Record<string, unknown> {
	const schemaStr = JSON.stringify(schema);

	// Replace invalid TupleUnit references with a valid null type
	// This handles ApiResponse<()> which utoipa doesn't handle correctly
	const fixed = schemaStr.replace(
		/\{"?\$ref"?:\s*"#\/components\/schemas\/TupleUnit"\}/g,
		'{"type": "null"}'
	);

	return JSON.parse(fixed);
}

async function generate() {
	console.log('Reading OpenAPI spec from:', OPENAPI_PATH);

	if (!fs.existsSync(OPENAPI_PATH)) {
		console.error('OpenAPI spec not found at:', OPENAPI_PATH);
		console.error('Make sure to run the backend to generate the spec first.');
		process.exit(1);
	}

	let schema = JSON.parse(fs.readFileSync(OPENAPI_PATH, 'utf-8'));

	// Fix known schema issues
	console.log('Fixing known schema issues...');
	schema = fixSchema(schema);

	console.log('Generating TypeScript types...');
	const ast = await openapiTS(schema, {
		// Add helpful comments from descriptions
		commentHeader: `/**
 * This file is auto-generated by scripts/generate-api-types.ts
 * Do not edit manually. Regenerate with: npm run generate:api
 */`
	});

	const output = astToString(ast);

	// Ensure output directory exists
	const outputDir = path.dirname(OUTPUT_PATH);
	if (!fs.existsSync(outputDir)) {
		fs.mkdirSync(outputDir, { recursive: true });
	}

	fs.writeFileSync(OUTPUT_PATH, output);
	console.log('Generated types at:', OUTPUT_PATH);
}

generate().catch((error) => {
	console.error('Failed to generate types:', error);
	process.exit(1);
});
