// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoveryPhase } from "./DiscoveryPhase";
import type { DiscoveryType } from "../../ui/src/lib/generated/DiscoveryType";

/**
 * Progress update from daemon to server during discovery
 */
export type DiscoveryUpdatePayload = { session_id: string, daemon_id: string, network_id: string, phase: DiscoveryPhase, discovery_type: DiscoveryType, progress: number, error: string | null, started_at: string | null, finished_at: string | null, };
